# Generated by Django 5.0.2 on 2024-02-15 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='admin@123', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('userType', models.CharField(choices=[('user', 'user'), ('teacher', 'teacher')], default='user', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sem_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=25)),
                ('semimage', models.ImageField(default='default.jpg', upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='branch_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('bimage', models.ImageField(default='default.jpg', upload_to='photos')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='subject_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('subimage', models.ImageField(default='default.jpg', upload_to='photos')),
                ('branch_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.branch_table')),
                ('sem_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.sem_table')),
            ],
        ),
        migrations.CreateModel(
            name='material_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_desc', models.CharField(max_length=250)),
                ('study_material', models.FileField(upload_to='material')),
                ('branch_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.branch_table')),
                ('sem_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.sem_table')),
                ('sub_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.subject_table')),
            ],
        ),
        migrations.CreateModel(
            name='book_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_desc', models.CharField(max_length=250)),
                ('book_file', models.FileField(upload_to='pdfs')),
                ('branch_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.branch_table')),
                ('sem_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.sem_table')),
                ('sub_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.subject_table')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('subject', models.CharField(blank=True, max_length=15, null=True)),
                ('bio', models.TextField(blank=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=128)),
                ('enrollment', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('branch', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_desc', models.CharField(max_length=250)),
                ('video', models.FileField(upload_to='videos')),
                ('branch_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.branch_table')),
                ('sem_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.sem_table')),
                ('sub_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.subject_table')),
            ],
        ),
    ]
