# Generated by Django 5.0.2 on 2024-02-16 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_table_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_table',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table'),
        ),
        migrations.AddField(
            model_name='videos',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table'),
        ),
    ]
