# Generated by Django 5.0.2 on 2024-02-19 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_complain_dought'),
    ]

    operations = [
        migrations.AddField(
            model_name='dought',
            name='teacher_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.teacher'),
        ),
        migrations.AlterField(
            model_name='dought',
            name='status',
            field=models.CharField(choices=[('Resolve', 'Resolve'), ('Not Resolve', 'Not resolve')], max_length=30),
        ),
    ]
