# Generated by Django 5.0.2 on 2024-02-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_dought_teacher_id_alter_dought_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dought',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
