# Generated by Django 5.0.2 on 2024-02-20 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_teacher_id_dought_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='teacher',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.teacher'),
        ),
    ]
