# Generated by Django 5.0.2 on 2024-03-14 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_complain_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], max_length=20)),
                ('payment_method', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Card_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=30)),
                ('card_number', models.CharField(default='', max_length=16)),
                ('cvv', models.IntegerField()),
                ('card_expiry_date', models.CharField(default='', max_length=20)),
                ('card_balance', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='Order_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('placed', 'placed'), ('pending', 'pending'), ('complete', 'complete')], default='', max_length=20)),
                ('amount', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subscriptionplan_table')),
            ],
        ),
        migrations.CreateModel(
            name='payment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=10)),
                ('status1', models.CharField(choices=[('placed', 'placed'), ('pending', 'pending'), ('complete', 'complete')], default='', max_length=20)),
                ('time', models.DateTimeField()),
                ('a_amount', models.FloatField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order_table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
    ]
