# Generated by Django 5.0.2 on 2024-03-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_usersubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='plan',
            new_name='plan_id',
        ),
        migrations.RenameField(
            model_name='usersubscription',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan_table',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan_table',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan_table',
            name='status',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
