# Generated by Django 5.0 on 2024-03-15 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_plan_usersubscription_plan_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_table',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usersubscription'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Order_table',
        ),
    ]
