from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('signup',views.signup, name='signup'),
    path('login',views.login, name='login'),
    path('Teachersignup', views.Teachersignup, name='TeacherSignup'),
    path('teacherdata1', views.teacherdata1, name='teacherdata'),
    path('userprofile', views.userprofile, name='userprofile'),
    path('teacherprofile', views.teacherprofile, name='teacherprofile'),
    path('profile',views.profile,name='profile'),
    path('showteacher', views.showteacher, name='showteacher'),
    path('viewdata',views.viewdata,name='viewdata'),
    path('teacherdata', views.teacherdata, name='teacherdata'),
    path('changepw',views.changepw,name='changepw'),
    path('logout',views.logout,name='logout'),
    path('checkuser', views.checklogin, name='checkuser'),
    path('branches', views.branches, name='branches'),
    path('branchwisesem/<int:bwsid>', views.branchwisesem, name='branchwisesem'),
    path('subjectwisematerial/<int:swmid>', views.subjectwisematerial, name='subjectwisematerial'),
    path('viewbooks/<int:vbid>', views.viewbooks, name='viewbooks'),
    path('viewvideos/<int:vsid>', views.viewvideos, name='viewvideos'),
    path('viewmaterial/<int:vmid>', views.viewmaterial, name='viewmaterial'),
    path('sembranchwisedata', views.sembranchwisedata, name='sembranchwisedata'),
    path('teacherdescription', views.teacherdescription, name='teacherdescription'),
    path('teachermaterial', views.teachermaterial, name='teachermaterial'),
    path('teachervideo', views.teachervideo, name='teachervideo'),
    path('doughtsolve', views.doughtsolve, name="doughtsolve"),
    path('showdought', views.showdought, name="showdought"),
    path('updatedought/<int:did>', views.updatedought, name='updatedought'),
    path('complains', views.complains, name="complains"),
    path('edituser', views.edituser, name='edituser'),
    path('updateuser', views.updateuser, name='updateuser'),
    path('editteacher', views.editteacher, name='editteacher'),
    path('updateteacher', views.updateteacher, name='updateteacher'),
    path('plans', views.plans, name='plans'),
    path('userActivePlan', views.userActivePlan, name='userActivePlan'),
    path('payment/<int:id>', views.payment, name='payment'),
    path('checkpayment', views.checkpayment, name='checkpayment'),
]